name: CI

on: [push, pull_request]

jobs:

  testsuite:
    name: all tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - { php-version: '8.2', typo3-version: '^13.4' }
          - { php-version: '8.3', typo3-version: '^13.4' }
          # Not tested yet, e.g. cs fixer is not compatible yet
          # - { php-version: '8.4', typo3-version: '^13.4' }

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          tools: composer:v2

      - name: Install
        run: |-
          composer require --no-interaction --prefer-dist --no-progress "typo3/cms-core:${{ matrix.typo3-version }}" "typo3/cms-form:${{ matrix.typo3-version }}"

      - name: Lint PHP
        run: composer run ci:php:lint

      - name: PHP Coding Standards Fixer
        run: composer run ci:php:cs

      - name: PHPStan
        run: composer run ci:php:stan

      - name: PHP Mess Detector
        run: composer run ci:php:md

      - name: Unit tests
        run: composer run ci:test:unit
